spring.application.name=zona-d-api
server.port=${PORT:8080}

# Escuchar en todas las interfaces de red (0.0.0.0 y NO 127.0.0.1)
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
